FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# benz-api

本文档主要用于Benz星徽尊享项目，提供App及Wechat调用（Wechat包括公众号及微信小程序）


- 统一接口格式如下，定义了http的请求头部及返回信息标准

~~~
请求URI: /api/v{version}/{controller}/{action}   //例如/api/v1/user/get

Headers: 
  + ft-token: token //用户通过用户名与密码登陆到服务器后返回的用户唯一令牌，在用户登录时返回，app需要本地保存
  + ft-device:app-ver=app1.0;device=android;device-name=xiaomi miui6.0;    //请求来源app或者web或者miniapp,比如：app1.0,web1.0等
Request:
  + sign:数据签名   //暂时不启用
  + data:
    {
        ......,
        ......,
        size:10,  //每页的数量，当有分页需求时候有此参数
        page:1,   //分页后的第几页,当有分页需求时候有此参数
    }
Response:
  + _metadata:{code:200,message:"提交成功"}  //接口基础信息
  + data:       //接口的业务信息
    {
        .....,
        items:[
            {item1:"",html:""},
            {item2:"",html:""}
        ],          //如果
        total:100,  //数据总数，当有分页需求时候有此参数
        size:10     //分页的大小，当有分页需求时候有此参数
    } 
  
~~~

设备类型:
| id | 设备类型 |
|---|---|
| 1 | android |
| 2 | ios |
| 3 | web |

- AccessToken设计

使用JWT规范生成AccessToken, 格式为 *Header,Claims,Signature*组成，生成结果可能如下：
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGFpbTEiOjAsImNsYWltMiI6ImNsYWltMi12YWx1ZSJ9.8pwBI_HtXqI3UgQHQ_rDRnSQRxFL1SR8fbQoS-5kM5s

~~~
Header：{"typ": "JWT","alg": "HS256"}   //头部，即JOSE Header
Claims：{userid:1000234,timestamp:unixtime,expirationtime:unixtime}   //声明，即JWS Paylao
Signature：mcsha签名，//即JWS Signature
~~~

1. **JWT**:https://www.jianshu.com/p/bc8d48842eea

2. **Asp.Net JWT类库**：https://github.com/jwt-dotnet/jwt

- asp.net版本设计

**版本设计**
~~~
/api/v[version]/{controller}/action     //version为1.0，2.0，3.0等
~~~

1. 类库：https://github.com/Microsoft/aspnet-api-versioning
 
2. http://www.cnblogs.com/tdfblog/p/asp-net-core-api-versioning.html

**版本更新原则**
1. 新版本接口迭代时，应该考虑兼容低版本。

2. 如果新版本中只是添加了一些字段， 对业务影响不大，可在低版本接口中直接添加字段。

3. 如果新版本中修改的字段对低版本影响不大，并且产品和测试确认可以接受，也可在低版本接口中直接修改。

4. 其它情况，一律以新版本接口开发。

- 系统状态返回码

**常用错误状态码**为3位长度定义，**业务错误状态码**为4位长度定义，具体如下：

| 错误码 | 错误描述 |
|---|---|
| 200 | 返回成功 |
| 401 | 用户未认证，请求失败 |
| 403 | 用户无权限访问该资源，请求失败 |
| 500 | 服务器程序错误 |
| 1100 | 用户相关接口错误（范围1100-1199） |
| 1300 | 订单及支付相关接口错误（范围1300-1399） |
| 1500 | 第三方相关的接口错误（范围1900-1999） |


## 用户账号 [/api/account] 
app需要有自己的身份标识用来和平台交互。
客户端登录的时候在http头部附加设备信息，完成登录和设备注册工作。

### 登录 [POST]
+ Request (application/json)

    + Headers
    
            ft-device:app-ver=app1.0;device=android;device-name=xiaomi miui6.0;device-id=as124-adf32-adfw
        
    + Body
    
            {
                "deviceid":"imei",
                "username":"test",
                "password":"test"
            }

+ Response 200 (application/json)

    + Body

            {
                "_metadata":{"code":200,"message":"ok"},
                "data":
                {
                    "userid":12,
                    "nickname":"test",
                    "token":"dummytoken"
                }
            }